
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/STARTER-team01
owner: ucsb-cs156-f25
repo_name: STARTER-team01
pull_requests: [{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-addCodeFormatter","number":17,"title":"Adding a Code Formatter","url":"https://github.com/ucsb-cs156-f25/STARTER-team01/pull/17"},{"author":{"is_bot":true,"login":"app/copilot-swe-agent"},"headRefName":"copilot/fix-15","number":16,"title":"Rename workflow 16 to 17 and convert to reusable workflow","url":"https://github.com/ucsb-cs156-f25/STARTER-team01/pull/16"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-unused-variables","number":14,"title":"pc - remove unused variable","url":"https://github.com/ucsb-cs156-f25/STARTER-team01/pull/14"}]
