
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/STARTER-team01
owner: ucsb-cs156-f25
repo_name: STARTER-team01
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-fix-swagger-login-link","number":19,"title":"pc - fix login link in header for swagger","url":"https://github.com/ucsb-cs156-f25/STARTER-team01/pull/19"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-fixFormatting","number":18,"title":"dj - fixed formatting on TestJob.java","url":"https://github.com/ucsb-cs156-f25/STARTER-team01/pull/18"}]
