
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/STARTER-team01
owner: ucsb-cs156-f25
repo_name: STARTER-team01
pull_requests: [{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-enforceWithoutBadChange","number":109,"title":"Workflow to Validate Migration Files","url":"https://github.com/ucsb-cs156-f25/STARTER-team01/pull/109"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-validateEntities","number":108,"title":"Workflow to Validate Migration Files [With Bad Change]","url":"https://github.com/ucsb-cs156-f25/STARTER-team01/pull/108"}]
