# This workflow will build a Java project with Maven and run PMD static analysis
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: "16-backend-PMD-checks: Java Code Analysis with PMD"

on:
  workflow_dispatch:
  pull_request:
    paths: [src/**, pom.xml, lombok.config, pmd-rules.xml]
  push:
    branches: [ main ]
    paths: [src/**, pom.xml, lombok.config, pmd-rules.xml]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Java (version from .java-version file)
      uses: actions/setup-java@v4
      with:
         distribution: semeru # See: https://github.com/actions/setup-java#supported-distributions
         java-version-file: ./.java-version
  
    - name: Build and run PMD analysis
      env:
        TEST_PROPERTIES: ${{ secrets.TEST_PROPERTIES }}
      run: mvn -B compile pmd:check